# Generated by Django 2.1.2 on 2018-10-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(height_field=100, upload_to='static/pic/', width_field=100),
        ),
    ]
