# Generated by Django 2.1.2 on 2018-10-30 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, height_field='100', upload_to='static/pic/', width_field='100'),
            preserve_default=False,
        ),
    ]
